on:
  push:
    branches:    
      - main

jobs:
  build:
    runs-on: ubuntu-latest

jobs:
  build:
    runs-on: ubuntu-latest
      - name: Build website
        run: yarn build
        working-directory: ./website
      - name: Export website
        run: yarn next export
        working-directory: ./website
      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/out
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'chore: 🚀 deploy'